name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  auto-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: deploy website
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          repository-name: vijaisuria/vijaisuria.github.io
          branch: gh-pages
          clean: true
          folder: .
